name: Manhunt
version: 0.0.1
author: Mark Bromell
main: com.markbromell.manhunt.Manhunt
api-version: 1.16

commands:
  hunter:
    description: Alter the roles of the players that are hunters
    usage: /hunter [add | remove | list] [<player1> <player2>...]

  hunted:
    desciption: Set the player to be hunted
    usage: /hunted <player>