name: Manhunt
version: 0.0.1
author: Mark Bromell
main: com.markbromell.manhunt.Manhunt
api-version: 1.16

commands:
  hunter:
    description: Adds players as hunters
    usage: /hunter [add | remove | list] [<player1> <player2>...]

  hunted:
    desciption: Set the player to be hunted
    usage: /hunted <player>

  start:
    description: Starts the manhunt
    usage: /start

  end:
    description: Ends the manhunt
    usage: /end